/**
 * Terms of Use Page
 *
 * Terms of service page for The Rheii / Rheii
 *
 * Features:
 * - Navigation bar
 * - Terms of use content with numbered sections
 * - Footer
 *
 * Design: Extracted from Figma (node-id: 581-3841)
 */

import Navigation from '@/components/landing/Navigation';
import LandingFooter from '@/components/landing/LandingFooter';

export default function TermsOfUsePage() {
  return (
    <main className="min-h-screen bg-parchment">
      {/* Navigation */}
      <Navigation />

      {/* Content */}
      <div className="max-w-[640px] mx-auto px-5 sm:px-4 pt-[160px] pb-[80px]">
        {/* Header */}
        <div className="flex flex-col gap-[10px] mb-[48px] pb-[32px] border-b border-stone">
          <p className="eyebrow">Legal</p>
          <h1 className="font-serif font-medium text-[36px] leading-[1.1] tracking-heading text-ink">
            Terms of Service
          </h1>
          <p className="mono-tag mt-[8px]">Last updated December 2025</p>
        </div>

        {/* 1. Acceptance of These Terms */}
        <section className="flex flex-col gap-[20px] mb-[48px]">
          <h2
            className="font-serif font-medium text-[23px] leading-[30px] text-[#322d29]"
            style={{
              fontVariationSettings: "'opsz' 14",
            }}
          >
            1. Acceptance of These Terms
          </h2>
          <div
            className="font-body text-[16px] leading-[24px] text-[#322d29]"
            style={{
              fontVariationSettings: "'opsz' 14",
            }}
          >
            <p className="mb-4">
              Please read these terms carefully. They form a legally binding agreement between you
              and Rheii.
            </p>
            <p className="mb-4">
              Rheii is not a mental healthcare provider, and the Services do not offer diagnosis,
              treatment, or clinical care. Any information, prompts, or insights provided through
              the Services are intended for educational, reflective, and wellness purposes only, and
              are not a substitute for professional advice.
            </p>
            <p className="mb-4">
              The Services use artificial intelligence (AI) to generate reflections, summaries, and
              insights. By using the Services, you consent to your journal content, responses, and
              interactions being processed, stored, and used as described in these Terms and in our
              Privacy Policy.
            </p>
            <p>If you do not agree to these Terms, you may not access or use the Services.</p>
          </div>
        </section>

        {/* 2. Use of Services */}
        <section className="flex flex-col gap-[20px] mb-[48px]">
          <h2
            className="font-serif font-medium text-[23px] leading-[30px] text-[#322d29]"
            style={{
              fontVariationSettings: "'opsz' 14",
            }}
          >
            2. Use of Services
          </h2>
          <div
            className="font-body text-[16px] leading-[24px] text-[#322d29]"
            style={{
              fontVariationSettings: "'opsz' 14",
            }}
          >
            <p className="mb-4">
              Rheii provides a journaling and personal-growth platform that offers AI-powered
              prompts, reflections, pattern detection, emotional awareness tools, and behavioural
              insights designed to support users in developing deeper self-understanding and more
              intentional personal growth.
            </p>
            <p className="mb-4">
              Rheii is not a mental health or medical service. The Services do not diagnose, treat,
              or prevent any mental health condition. Any AI-generated guidance, summaries, or
              insights are for reflective and educational use only. No therapeutic, psychological,
              or clinical relationship is created.
            </p>
            <p className="mb-4">
              You are solely responsible for decisions you make using information from the Services.
            </p>
            <p className="mb-4">
              If you are experiencing mental health distress, a crisis, or thoughts of self-harm or
              harm to others, seek immediate help from a qualified professional or call your local
              emergency line. The Services are not designed for crisis management.
            </p>
            <p>
              Rheii does not guarantee the accuracy of any content generated by the Services.
              Information may be incomplete, outdated, or imprecise. You should review any personal
              decisions with appropriate professionals when relevant.
            </p>
          </div>
        </section>

        {/* 3. Eligibility and Accounts */}
        <section className="flex flex-col gap-[20px] mb-[48px]">
          <h2
            className="font-serif font-medium text-[23px] leading-[30px] text-[#322d29]"
            style={{
              fontVariationSettings: "'opsz' 14",
            }}
          >
            3. Eligibility and Accounts
          </h2>
          <div
            className="font-body text-[16px] leading-[24px] text-[#322d29]"
            style={{
              fontVariationSettings: "'opsz' 14",
            }}
          >
            <p className="mb-4">You must be at least 18 years old to use Rheii.</p>
            <p className="mb-4">To use Rheii, you agree to:</p>
            <div className="flex flex-col gap-[8px] mb-4">
              <div className="flex gap-[8px]">
                <span className="font-inter text-[16px] leading-[28px] text-[#242424] w-[17px]">
                  a)
                </span>
                <p className="flex-1">provide accurate account information,</p>
              </div>
              <div className="flex gap-[8px]">
                <span className="font-inter text-[16px] leading-[28px] text-[#242424] w-[17px]">
                  b)
                </span>
                <p className="flex-1">keep login credentials secure, and</p>
              </div>
              <div className="flex gap-[8px]">
                <span className="font-inter text-[16px] leading-[28px] text-[#242424] w-[17px]">
                  c)
                </span>
                <p className="flex-1">notify us of any unauthorized account use.</p>
              </div>
            </div>
            <p>You are responsible for all activity under your account.</p>
          </div>
        </section>

        {/* 4. Privacy */}
        <section className="flex flex-col gap-[20px] mb-[48px]">
          <h2
            className="font-serif font-medium text-[23px] leading-[30px] text-[#322d29]"
            style={{
              fontVariationSettings: "'opsz' 14",
            }}
          >
            4. Privacy
          </h2>
          <div
            className="font-body text-[16px] leading-[24px] text-[#322d29]"
            style={{
              fontVariationSettings: "'opsz' 14",
            }}
          >
            <p className="mb-4">
              Please review our Privacy Policy, which explains what data we collect and how we use,
              store, and disclose it. By using the Services, you agree to the Privacy Policy.
            </p>
            <p className="mb-4">
              Rheii is not a HIPAA-regulated entity. Journal entries, insights, and emotional data
              processed through Rheii are not medical records.
            </p>
            <p>
              We may generate and use de-identified or aggregated data to improve Rheii's features,
              algorithms, and user experience.
            </p>
          </div>
        </section>

        {/* 5. Exports and Sharing */}
        <section className="flex flex-col gap-[20px] mb-[48px]">
          <h2
            className="font-serif font-medium text-[23px] leading-[30px] text-[#322d29]"
            style={{
              fontVariationSettings: "'opsz' 14",
            }}
          >
            5. Exports and Sharing
          </h2>
          <div
            className="font-body text-[16px] leading-[24px] text-[#322d29]"
            style={{
              fontVariationSettings: "'opsz' 14",
            }}
          >
            <p className="mb-4">
              The Services may allow you to export or share summaries, insights, or visualizations
              generated from your journaling ("Exports").
            </p>
            <p className="mb-4">You acknowledge that:</p>
            <ul className="list-disc pl-6 space-y-2 mb-4">
              <li>You choose who receives these Exports;</li>
              <li>Rheii is not responsible for what third parties do with them;</li>
              <li>
                Exports may contain AI-generated content and are not clinical, diagnostic, or expert
                documents.
              </li>
            </ul>
            <p>Revoking future sharing does not affect past Exports.</p>
          </div>
        </section>

        {/* 6. Independent Professionals */}
        <section className="flex flex-col gap-[20px] mb-[48px]">
          <h2
            className="font-serif font-medium text-[23px] leading-[30px] text-[#322d29]"
            style={{
              fontVariationSettings: "'opsz' 14",
            }}
          >
            6. Independent Professionals (If Applicable)
          </h2>
          <div
            className="font-body text-[16px] leading-[24px] text-[#322d29]"
            style={{
              fontVariationSettings: "'opsz' 14",
            }}
          >
            <p className="mb-4">
              Rheii may offer optional access to independent coaches, facilitators, or wellbeing
              practitioners ("Providers") for non-clinical guidance. These Providers are not
              employees or agents of Rheii.
            </p>
            <p className="mb-4">
              Rheii does not supervise, endorse, or control their advice. They are solely
              responsible for their own services.
            </p>
            <p>
              Any interaction with Providers is governed by the Provider's own terms, and any
              payments are made directly to them. Rheii is not liable for their acts or omissions.
            </p>
          </div>
        </section>

        {/* 7. License and Acceptable Use */}
        <section className="flex flex-col gap-[20px] mb-[48px]">
          <h2
            className="font-serif font-medium text-[23px] leading-[30px] text-[#322d29]"
            style={{
              fontVariationSettings: "'opsz' 14",
            }}
          >
            7. License and Acceptable Use
          </h2>
          <div
            className="font-body text-[16px] leading-[24px] text-[#322d29]"
            style={{
              fontVariationSettings: "'opsz' 14",
            }}
          >
            <p className="mb-4">
              We grant you a limited, revocable, non-transferable license to use the Services for
              personal, non-commercial purposes.
            </p>
            <p className="mb-4">You may not:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Copy, reverse-engineer, or modify the Services</li>
              <li>Use Rheii to train competing AI models</li>
              <li>Access the Services in unauthorized ways</li>
              <li>Harass other users, impersonate others, or misuse interactive features</li>
              <li>Upload harmful, offensive, or illegal content</li>
              <li>Use the Services for illegal purposes</li>
            </ul>
          </div>
        </section>

        {/* 8. Intellectual Property */}
        <section className="flex flex-col gap-[20px] mb-[48px]">
          <h2
            className="font-serif font-medium text-[23px] leading-[30px] text-[#322d29]"
            style={{
              fontVariationSettings: "'opsz' 14",
            }}
          >
            8. Intellectual Property
          </h2>
          <div
            className="font-body text-[16px] leading-[24px] text-[#322d29]"
            style={{
              fontVariationSettings: "'opsz' 14",
            }}
          >
            <p className="mb-4">
              Rheii owns the intellectual property in the Services, including models, algorithms,
              interface designs, branding, and content.
            </p>
            <p className="mb-4">
              Any feedback you provide becomes Rheii's property without any obligation to compensate
              you.
            </p>
            <p className="mb-4">
              You retain ownership of the content you submit (e.g., journals, reflections). You
              grant Rheii a license to use that content to provide and improve the Services.
            </p>
            <p>
              Rheii also collects and owns Usage Data, which includes anonymous interaction
              patterns, feature usage, behaviour signals, and aggregated journaling metadata.
            </p>
          </div>
        </section>

        {/* 9. Subscriptions, Trials, Billing, and Renewals */}
        <section className="flex flex-col gap-[20px] mb-[48px]">
          <h2
            className="font-serif font-medium text-[23px] leading-[30px] text-[#322d29]"
            style={{
              fontVariationSettings: "'opsz' 14",
            }}
          >
            9. Subscriptions, Trials, Billing, and Renewals
          </h2>
          <div
            className="font-body text-[16px] leading-[24px] text-[#322d29]"
            style={{
              fontVariationSettings: "'opsz' 14",
            }}
          >
            <p className="mb-4">
              By subscribing, you authorize Rheii to charge your payment method on a recurring basis
              until you cancel.
            </p>
            <p className="mb-4">
              Subscriptions automatically renew at the then-current rate. Fees are typically
              non-refundable unless required by law.
            </p>
            <p>
              If you begin a trial and do not cancel before it ends, billing will begin
              automatically.
            </p>
          </div>
        </section>

        {/* 10. Third-Party Terms and AI Providers */}
        <section className="flex flex-col gap-[20px] mb-[48px]">
          <h2
            className="font-serif font-medium text-[23px] leading-[30px] text-[#322d29]"
            style={{
              fontVariationSettings: "'opsz' 14",
            }}
          >
            10. Third-Party Terms and AI Providers
          </h2>
          <div
            className="font-body text-[16px] leading-[24px] text-[#322d29]"
            style={{
              fontVariationSettings: "'opsz' 14",
            }}
          >
            <p className="mb-4">
              If you download Rheii from Apple or Google, their terms apply in addition to these
              Terms.
            </p>
            <p>
              We may use third-party AI providers and infrastructure partners to power certain
              features. By using Rheii, you consent to your data being processed by those providers
              for the purpose of delivering and improving the Services.
            </p>
          </div>
        </section>

        {/* 11. Changes */}
        <section className="flex flex-col gap-[20px] mb-[48px]">
          <h2
            className="font-serif font-medium text-[23px] leading-[30px] text-[#322d29]"
            style={{
              fontVariationSettings: "'opsz' 14",
            }}
          >
            11. Changes
          </h2>
          <p
            className="font-body text-[16px] leading-[24px] text-[#322d29]"
            style={{
              fontVariationSettings: "'opsz' 14",
            }}
          >
            We may update or modify the Services or these Terms at any time. Material changes will
            be communicated through the app or website. Continued use after changes constitutes
            acceptance.
          </p>
        </section>

        {/* 12. Disclaimers */}
        <section className="flex flex-col gap-[20px] mb-[48px]">
          <h2
            className="font-serif font-medium text-[23px] leading-[30px] text-[#322d29]"
            style={{
              fontVariationSettings: "'opsz' 14",
            }}
          >
            12. Disclaimers
          </h2>
          <div
            className="font-body text-[16px] leading-[24px] text-[#322d29]"
            style={{
              fontVariationSettings: "'opsz' 14",
            }}
          >
            <p className="mb-4">THE SERVICES ARE PROVIDED "AS IS" AND "AS AVAILABLE."</p>
            <p className="mb-4">
              RHEII DISCLAIMS ALL WARRANTIES, INCLUDING ACCURACY, FITNESS FOR A PARTICULAR PURPOSE,
              AND NON-INFRINGEMENT.
            </p>
            <p className="mb-4">YOU ACKNOWLEDGE THAT</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>AI outputs may be incomplete, imprecise, or incorrect</li>
              <li>Reflective insights are not psychological or therapeutic advice</li>
              <li>We do not guarantee uninterrupted or error-free access</li>
              <li>You should not rely on AI insights for high-stakes decisions</li>
              <li>Rheii does not provide crisis support</li>
            </ul>
          </div>
        </section>

        {/* 13. Limitation of Liability */}
        <section className="flex flex-col gap-[20px] mb-[48px]">
          <h2
            className="font-serif font-medium text-[23px] leading-[30px] text-[#322d29]"
            style={{
              fontVariationSettings: "'opsz' 14",
            }}
          >
            13. Limitation of Liability
          </h2>
          <div
            className="font-body text-[16px] leading-[24px] text-[#322d29]"
            style={{
              fontVariationSettings: "'opsz' 14",
            }}
          >
            <p className="mb-4">
              To the maximum extent permitted by law, Rheii is not liable for indirect, incidental,
              consequential, or punitive damages.
            </p>
            <p>
              If Rheii is found liable, our total liability will not exceed:{' '}
              <span className="font-bold">
                (i) USD $100 or (ii) the amount you paid in the past 6 months,
              </span>{' '}
              whichever is greater.
            </p>
          </div>
        </section>

        {/* 14. Indemnification */}
        <section className="flex flex-col gap-[20px] mb-[48px]">
          <h2
            className="font-serif font-medium text-[23px] leading-[30px] text-[#322d29]"
            style={{
              fontVariationSettings: "'opsz' 14",
            }}
          >
            14. Indemnification
          </h2>
          <div
            className="font-body text-[16px] leading-[24px] text-[#322d29]"
            style={{
              fontVariationSettings: "'opsz' 14",
            }}
          >
            <p className="mb-4">You agree to indemnify Rheii for claims arising from:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Your misuse of the Services</li>
              <li>Your violation of these Terms</li>
              <li>Your sharing or disclosure of Exports</li>
              <li>Any disputes between you and third parties</li>
            </ul>
          </div>
        </section>

        {/* 15. Dispute Resolution and Arbitration */}
        <section className="flex flex-col gap-[20px] mb-[48px]">
          <h2
            className="font-serif font-medium text-[23px] leading-[30px] text-[#322d29]"
            style={{
              fontVariationSettings: "'opsz' 14",
            }}
          >
            15. Dispute Resolution and Arbitration
          </h2>
          <div
            className="font-body text-[16px] leading-[24px] text-[#322d29]"
            style={{
              fontVariationSettings: "'opsz' 14",
            }}
          >
            <p className="mb-4">
              By using Rheii, you agree to resolve disputes through binding arbitration rather than
              court, except in certain limited cases.
            </p>
            <p>
              This section mirrors the structure of standard consumer arbitration clauses and can be
              customized further depending on jurisdiction.
            </p>
          </div>
        </section>

        {/* 16. Termination */}
        <section className="flex flex-col gap-[20px] mb-[48px]">
          <h2
            className="font-serif font-medium text-[23px] leading-[30px] text-[#322d29]"
            style={{
              fontVariationSettings: "'opsz' 14",
            }}
          >
            16. Termination
          </h2>
          <div
            className="font-body text-[16px] leading-[24px] text-[#322d29]"
            style={{
              fontVariationSettings: "'opsz' 14",
            }}
          >
            <p className="mb-4">
              We may suspend or terminate your access if you violate these Terms. You may stop using
              the Services at any time.
            </p>
            <p>Certain sections survive termination.</p>
          </div>
        </section>

        {/* 17. Miscellaneous */}
        <section className="flex flex-col gap-[20px] mb-[48px]">
          <h2
            className="font-serif font-medium text-[23px] leading-[30px] text-[#322d29]"
            style={{
              fontVariationSettings: "'opsz' 14",
            }}
          >
            17. Miscellaneous
          </h2>
          <div
            className="font-body text-[16px] leading-[24px] text-[#322d29]"
            style={{
              fontVariationSettings: "'opsz' 14",
            }}
          >
            <p className="mb-4">Includes standard legal terms on:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Entire agreement</li>
              <li>Severability</li>
              <li>Assignment</li>
              <li>Notices</li>
              <li>Force majeure</li>
              <li>Electronic communications</li>
            </ul>
          </div>
        </section>

        {/* 18. Contact */}
        <section className="flex flex-col gap-[20px] mb-[48px]">
          <h2
            className="font-serif font-medium text-[23px] leading-[30px] text-[#322d29]"
            style={{
              fontVariationSettings: "'opsz' 14",
            }}
          >
            18. Contact
          </h2>
          <p
            className="font-body text-[16px] leading-[24px] text-[#322d29]"
            style={{
              fontVariationSettings: "'opsz' 14",
            }}
          >
            For legal or support inquiries:
            <br />
            Email:{' '}
            <a href="mailto:hello@rheii.com" className="underline hover:opacity-70">
              hello@rheii.com
            </a>
          </p>
        </section>
      </div>

      {/* Footer */}
      <LandingFooter />
    </main>
  );
}
